// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    daily_summary: {
        name: "daily_summary";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          trip_date: string;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_duration_minutes: number;
          /** @sqlType DOUBLE */
          avg_distance_km: number;
          /** @sqlType DOUBLE */
          total_distance_km: number;
        }>;
      };
    trip_bounds: {
        name: "trip_bounds";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          first_trip_date: string;
          /** @sqlType DATE */
          last_trip_date: string;
          /** @sqlType TIMESTAMP */
          last_event_time: string;
          /** @sqlType BIGINT */
          total_trip_count: number;
        }>;
      };
    trip_totals: {
        name: "trip_totals";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_duration_minutes: number;
          /** @sqlType DOUBLE */
          avg_distance_km: number;
          /** @sqlType DOUBLE */
          total_distance_km: number;
          /** @sqlType DOUBLE */
          total_duration_minutes: number;
        }>;
      };
    trips: {
        name: "trips";
        parameters: {
          /** DATE - use sql.date() */
          start_date: SQLDateMarker;
          /** DATE - use sql.date() */
          end_date: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType INT */
          start_event_id: number;
          /** @sqlType INT */
          end_event_id: number;
          /** @sqlType TIMESTAMP */
          start_time: string;
          /** @sqlType TIMESTAMP */
          end_time: string;
          /** @sqlType DOUBLE */
          duration_minutes: number;
          /** @sqlType DOUBLE */
          distance_km: number;
          /** @sqlType DOUBLE */
          start_latitude: number;
          /** @sqlType DOUBLE */
          start_longitude: number;
          /** @sqlType DOUBLE */
          end_latitude: number;
          /** @sqlType DOUBLE */
          end_longitude: number;
        }>;
      };
  }
}
