resources:
  pipelines:
    trip_pipeline:
      name: "${bundle.name}-pipeline"
      catalog: ${var.catalog}
      schema: ${var.schema}
      serverless: true
      continuous: false
      libraries:
        - glob:
            include: ../src/pipeline/**
